site_name: 我的知识库
site_description: 教程与工具知识库
site_url: https://你的用户名.github.io/你的仓库名/

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换到深色模式

    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式
nav:
  - 首页: index.md
  - 视频配套文档:
      - "1 👉白嫖 ChatGPT Plus 会员！GPT 5.2、Codex 免费用！": PT/20251220_30_gpt.md
      - "2 Googl 邮箱注册教程&避坑指南": PT/20251223_31_gmail.md 
      - "3 🍏史上最快的苹果美区账号注册方法": PT/20251226_32_Apple.md
      - "4 🥸Gemini 3 Pro学生认证，免费使用一年！丨订阅全流程教程！丨避坑指南！": PT/20260113_039_Gemini students.md
      - "5 👉（小火箭）Shadowrocket保姆级教程：免费下载+「懒人配置」让节点自动切换！": PT/20260128_001_Shadowrocket.md
      - "6 🎁Gemini教程｜Pixel活动免费领取 Google AI Pro 12个月｜无需 Pixel 设备": PT/20260317_05_Gemini.md 
      - "7 👉Gemini 学生认证免费，即将截止！最后窗口期 + 3 个稳定替代方案！": PT/20260122_041_Gemini.md
      - "8 🤑免费领一年 ChatGPT Plus！大兵认证保姆级教程！｜省 240 刀 + 解锁 Sora/Codex丨GPT Plus军人认证（电报）": PT/20260108_037_gptplus.md
      - "9 👉👉👉ChatGPT 5.2 正式上线！速度飞快，效果惊人！免费获取5.2版教程！": PT/20260313_06_gpt52.md
      - "10 👉👉👉Gemini 3.5 Pro 免费体验！丨快速开启你的AI之旅！": PT/20260313_07_Gemini35.md
      1
        - 常用工具（自取）:
      - "1 👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉👉
