site_name: 我的知识库
site_description: 教程与工具知识库
site_url: https://你的用户名.github.io/你的仓库名/

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换到深色模式

    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式
nav:
  - 首页: index.md
  - 视频配套文档:
      - 1 "白嫖 ChatGPT Plus 会员!GPT 5.2、Codex 免费用!": /PT/20251220_30_gpt.md
  - 个人推荐:
      - 2 入门: TJ/02.md 
  - 常用工具（自取）:
      - 3 入门: tools/03.md
  - 关于: about.md
2